# Generated by Django 5.1.6 on 2025-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('eleve', 'Élève'), ('parent', 'Parent'), ('directeur', 'Directeur'), ('secretaire', 'Secrétaire'), ('surveillant', 'Surveillant')], db_index=True, max_length=20, verbose_name='Rôle'),
        ),
    ]
