# Generated by Django 5.2.4 on 2025-08-28 18:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='coefficient',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3, verbose_name='Coefficient'),
        ),
    ]
