# Generated by Django 5.2.4 on 2025-08-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_note_coefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('NOTE', 'Nouvelle note'), ('ABSENCE', 'Nouvelle absence'), ('MESSAGE', 'Nouveau message'), ('PAIEMENT', 'Paiement enregistré'), ('AGENDA', 'Événement agenda'), ('AUTRE', 'Autre')], db_index=True, max_length=20, verbose_name='Type de notification')),
                ('objet', models.CharField(max_length=100, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='Lien associé')),
                ('statut', models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('ARCHIVE', 'Archivé')], db_index=True, default='NON_LU', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('priorite', models.PositiveSmallIntegerField(default=1, verbose_name='Priorité')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'statut'], name='home_notifi_utilisa_f0c717_idx'), models.Index(fields=['type_notification'], name='home_notifi_type_no_af9941_idx')],
            },
        ),
    ]
