# Generated by Django 5.2.4 on 2025-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('REMBOURSE', 'Remboursé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
