# Generated by Django 5.2.4 on 2025-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_paiement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Date d'inscription"),
        ),
    ]
