# Generated by Django 5.2.4 on 2025-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_eleve_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('INSCRIT', 'Inscrit'), ('EN_ATTENTE', 'En attente'), ('SUSPENDU', 'Suspendu'), ('EXCLUE', 'Exclu'), ('TRANSFERE', 'Transféré')], db_index=True, default='INSCRIT', max_length=20, verbose_name='Statut'),
        ),
    ]
