# Generated by Django 5.2.4 on 2025-08-30 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_eleve_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='retard',
            field=models.BooleanField(default=False, verbose_name='Retard'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='home.eleve'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='justification',
            field=models.TextField(blank=True, null=True, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='present',
            field=models.BooleanField(default=True, verbose_name='Présent'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date'], name='home_presen_date_6d8d79_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['present'], name='home_presen_present_a0913c_idx'),
        ),
    ]
