# Generated by Django 5.2.4 on 2025-08-30 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_presence_retard_alter_presence_eleve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression')], db_index=True, max_length=20, verbose_name='Type de transaction')),
                ('objet', models.CharField(max_length=100, verbose_name='Objet')),
                ('objet_id', models.IntegerField(null=True, verbose_name="ID de l'objet")),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='frais',
            options={'ordering': ['date_limite'], 'verbose_name': 'Frais', 'verbose_name_plural': 'Frais'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.RemoveField(
            model_name='frais',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='description',
        ),
        migrations.AddField(
            model_name='frais',
            name='categorie',
            field=models.CharField(choices=[('INSCRIPTION', "Frais d'inscription"), ('SCOLARITE', 'Frais de scolarité'), ('EXAMEN', "Frais d'examen"), ('LIVRE', 'Frais de livres'), ('AUTRE', 'Autre')], db_index=True, default='10:12', max_length=20, verbose_name='Catégorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frais',
            name='description',
            field=models.CharField(default='12:30', max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frais',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiellement payé'), ('PAYE', 'Payé'), ('EXEMPT', 'Exempté')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='frais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='home.frais', verbose_name='Frais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='frais',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='frais',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_niveau', to='home.niveau', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='home.eleve', verbose_name='Élève'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen',
            field=models.CharField(choices=[('ESPECE', 'Espèce'), ('MOBILE_MONEY', 'Mobile Money'), ('BANQUE', 'Virement bancaire'), ('CHEQUE', 'Chèque')], max_length=20, verbose_name='Moyen de paiement'),
        ),
        migrations.AddIndex(
            model_name='frais',
            index=models.Index(fields=['niveau', 'date_limite'], name='home_frais_niveau__345a63_idx'),
        ),
        migrations.AddIndex(
            model_name='frais',
            index=models.Index(fields=['statut'], name='home_frais_statut_102815_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='home_paieme_statut_4026cf_idx'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['utilisateur', 'date'], name='home_transa_utilisa_9d0211_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type_transaction'], name='home_transa_type_tr_650c47_idx'),
        ),
    ]
