# Generated by Django 5.2.4 on 2025-09-02 16:57

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_transaction_alter_frais_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.RemoveIndex(
            model_name='frais',
            name='home_frais_statut_102815_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='home_paieme_eleve_i_4bb23a_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='home_paieme_statut_4026cf_idx',
        ),
        migrations.RemoveField(
            model_name='frais',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='moyen',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='statut',
        ),
        migrations.AddField(
            model_name='message',
            name='archive',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime_destinataire',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Supprimé par le destinataire'),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime_expediteur',
            field=models.BooleanField(db_index=True, default=False, verbose_name="Supprimé par l'expéditeur"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='difference_rendue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Différence rendue'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant total dû'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_transaction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de transaction'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='personnel',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['secretaire', 'admin', 'directeur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personnel qui a enregistré le paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('Non payé', 'Non payé'), ('Partiellement payé', 'Partiellement payé'), ('Payé', 'Payé'), ('Exempté', 'Exempté'), ('En attente de validation', 'En attente de validation')], db_index=True, default='Non payé', max_length=30, verbose_name='Statut du paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money'), ('Airtel Money', 'Airtel Money'), ('Orange Money', 'Orange Money'), ('Moov Money', 'Moov Money'), ('Virement', 'Virement bancaire'), ('Chèque', 'Chèque'), ('Autre', 'Autre')], default='Espèces', max_length=30, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='frais',
            name='date_limite',
            field=models.DateField(db_index=True, verbose_name='Date limite'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='message',
            name='lu',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='objet',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Objet'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'lu', 'date_envoi'], name='home_messag_expedit_c55c89_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['destinataire', 'lu', 'date_envoi'], name='home_messag_destina_bab4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['eleve', 'date_paiement'], name='home_paieme_eleve_i_30c7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['status'], name='home_paieme_status_ed1a68_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('expediteur', models.F('destinataire')), _negated=True), name='expediteur_destinataire_different'),
        ),
    ]
