# Generated by Django 5.2.4 on 2025-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_paiement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('Payé', 'Payé'), ('Partiellement payé', 'Partiellement payé'), ('Non payé', 'Non payé')], db_index=True, default='Non payé', max_length=50, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['frais', 'eleve'], name='home_paieme_frais_i_27bc84_idx'),
        ),
    ]
