# Generated by Django 5.2.4 on 2025-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_paiement_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='home_notifi_utilisa_f0c717_idx',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='statut',
        ),
        migrations.AddField(
            model_name='eleve',
            name='status',
            field=models.CharField(choices=[('INSCRIT', 'Inscrit'), ('EN_ATTENTE', 'En attente'), ('SUSPENDU', 'Suspendu'), ('EXCLUE', 'Exclu'), ('TRANSFERE', 'Transféré')], db_index=True, default='INSCRIT', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('ARCHIVE', 'Archivé')], db_index=True, default='NON_LU', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('Payé', 'Payé'), ('Partiellement payé', 'Partiellement payé'), ('Non payé', 'Non payé')], db_index=True, default='Non payé', max_length=50, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'status'], name='home_notifi_utilisa_c95414_idx'),
        ),
    ]
