# Generated by Django 5.2.4 on 2025-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_notification_home_notifi_utilisa_f0c717_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='home_notifi_utilisa_c95414_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='home_paieme_frais_i_27bc84_idx',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('INSCRIT', 'Inscrit'), ('EN_ATTENTE', 'En attente'), ('SUSPENDU', 'Suspendu'), ('EXCLUE', 'Exclu'), ('TRANSFERE', 'Transféré')], db_index=True, default='INSCRIT', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='notification',
            name='statut',
            field=models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('ARCHIVE', 'Archivé')], db_index=True, default='NON_LU', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('Non payé', 'Non payé'), ('Partiellement payé', 'Partiellement payé'), ('Payé', 'Payé'), ('Exempté', 'Exempté'), ('En attente de validation', 'En attente de validation')], db_index=True, default='Non payé', max_length=30, verbose_name='Statut du paiement'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'statut'], name='home_notifi_utilisa_f0c717_idx'),
        ),
    ]
