# Generated by Django 5.2.4 on 2025-09-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_notification_home_notifi_utilisa_c95414_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('Payé', 'Payé'), ('Partiellement payé', 'Partiellement payé'), ('Non payé', 'Non payé')], db_index=True, default='Non payé', max_length=30, verbose_name='Statut du paiement'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='home.eleve'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['frais', 'eleve'], name='home_paieme_frais_i_27bc84_idx'),
        ),
    ]
